name: hello-world #workflow name
'on': push #event which is triggered and to workflow name
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
